version: '3.8'

services:
  spring-app:
    build: ./ChatBot_pj2
    container_name: chatbot_spring
    ports:
      - "8080:8080"
    depends_on:
      - ai-app
    networks:
      - chatbot-net

  ai-app:
    build: ./ChatBot_pj2_AI
    container_name: chatbot_ai
    ports:
      - "5001:5001"
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge
